apiVersion: v1
kind: Service
metadata:
  name: overseerr # This name is what other apps and the Ingress will use
  namespace: default
spec:
  selector:
    app: overseerr # Must match the label in your deployment.yaml
  type: ClusterIP # Standard for internal cluster traffic
  ports:
    - name: http
      protocol: TCP
      port: 5055 # The port exposed to the cluster
      targetPort: 5055 # The actual port Overseerr is listening on
