apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/CoreyC315/homelab-devops.git"
    path: kubernetes/apps/filebrowser # Points to your new folder
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default # FileBrowser will live in the default namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
