apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/CoreyC315/homelab-devops.git"
    path: kubernetes/apps/networking
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
