apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    chart: csi-driver-nfs
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: v4.9.0
    helm:
      values: |
        kubeletDir: /var/lib/k0s/kubelet
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # Drivers should live here for system-level access
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
