apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service # This MUST match the 'name' in your networking.yaml
  namespace: default
spec:
  selector:
    app: jellyfin # This MUST match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8096
