apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestash
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestash
  template:
    metadata:
      labels:
        app: filestash
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: filestash
          image: machines/filestash:latest
          ports:
            - containerPort: 8334
          volumeMounts:
            - name: data
              mountPath: /app/data/storage # This is where the files will live
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: filestash-pvc
