apiVersion: v1
kind: Service
metadata:
  name: filestash-service
  namespace: default
spec:
  selector:
    app: filestash
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8334
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filestash-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: files.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filestash-service
                port:
                  number: 80
