apiVersion: v1
kind: Service
metadata:
  name: filestash-service
  namespace: default
spec:
  selector:
    app: filestash
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8334
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filestash-ingress
  namespace: default
  metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # Finder requires these to handle large files and WebDAV methods
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    # This snippet allows the specific methods macOS uses
    nginx.ingress.kubernetes.io/configuration-snippet: |
      dav_methods PUT DELETE MKCOL COPY MOVE;
spec:
  rules:
    - host: files.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filestash-service
                port:
                  number: 80
