apiVersion: v1
kind: Service
metadata:
  name: sonarr # This name is what other apps and the Ingress will use
  namespace: default
spec:
  selector:
    app: sonarr # Must match the label in your deployment.yaml
  type: ClusterIP # Standard for internal cluster traffic
  ports:
    - name: http
      protocol: TCP
      port: 8989 # The port exposed to the cluster
      targetPort: 8989 # The actual port Sonarr is listening on
